apiVersion: v1
kind: Pod
metadata:
  name: map-feature-latest
  labels:
    app: map-feature-latest
spec:
  containers:
  - name: banco
    image: docker.io/postgis/postgis
    ports:
    - containerPort: 5432
    volumeMounts:  
    - name: initdatabase
      mountPath: /docker-entrypoint-initdb.d
    env: 
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: adminCredential
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: adminCredential
          key: password
    - name: POSTGRES_DB
      value: mapfeature
    - name: API_USERNAME
      valueFrom:
        secretKeyRef:
          name: apiCredential
          key: username
    - name: API_PASSWORD
      valueFrom:
        secretKeyRef:
          name: apiCredential
          key: password
  - name: nginx
    image: docker.io/library/nginx:latest
    ports:
    - containerPort: 80
      hostPort: 8000
    volumeMounts:  
    - name: build  
      mountPath: /usr/share/nginx/html 
    - name: conf  
      mountPath: /etc/nginx/conf.d/
  - name: api1
    image: arthurrabel/fastapi.with.geoalchemy:1.2
    ports:
    - containerPort: 81
    env:
    - name: API_USERNAME
      valueFrom:
        secretKeyRef:
          name: apiCredential
          key: username
    - name: API_PASSWORD
      valueFrom:
        secretKeyRef:
          name: apiCredential
          key: password
    command: ["/bin/sh", "-c"]
    args:
    - |
      /wait-for-it.sh banco:5432 --timeout=30 --strict;
      uvicorn main:app --host 0.0.0.0 --port 81
  - name: api2
    image: arthurrabel/fastapi.with.geoalchemy:1.2
    ports:
    - containerPort: 82
    env:
    - name: API_USERNAME
      valueFrom:
        secretKeyRef:
          name: apiCredential
          key: username
    - name: API_PASSWORD
      valueFrom:
        secretKeyRef:
          name: apiCredential
          key: password
    command: ["/bin/sh", "-c"]
    args:
    - |
      /wait-for-it.sh banco:5432 --timeout=30 --strict;
      uvicorn main:app --host 0.0.0.0 --port 82

  volumes:  
  - name: build  
    hostPath:  
      path: ./frontEnd/build
      type: Directory 
  - name: conf  
    hostPath:  
      path: ./frontEnd/nginx
      type: Directory 
  - name: initdatabase
    hostPath:  
      path: ./database
      type: Directory